### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by alfredw2016** [matteobustreo/dispev#1] opened 2016-12-23 01:11 UTC
I have executed your program and the parameter is "im0.png im1.png 60 1 3 3 5 9”, then I get the disparity as follow.
![disp](https://cloud.githubusercontent.com/assets/21237303/21445085/b66ed5a0-c8ef-11e6-919c-e17e1c2dd304.jpg)

**Comment by matteobustreo** [comment] 2017-04-12 15:17
Hello,
I'm not able to reproduce your output. 
Is the provided demo script Dispev.bat producing the expected output?

In case it does, please remember that my implementation of the matching algorithm for stereoscopic disparity evaluation is asymmetric: if you swap the inputs, the output will be incorrect since the algorithm will search for correspondence in one direction only. 
This might be the cause of your unexpected result.

**Closed as completed by matteobustreo** 2017-04-12 15:17 UTC
